### ISSUE TITLE
uninstalling Noctis & Silo

### ISSUE THREAD

**Issue by SeMoOo** [LaughingQuoll/NoctisXI#13]
after uninstalling Noctis and Silo especially, Silo creates an empty section on top of CC modules after uninstall which can't be reverted to normal. I can't download the deb file of Silo to know which file in the system is causing this empty space in CC

**Comment by Favna** [comment]
I recommend you put a more descriptive title for one because this title suggests you have an issue with uninstalling, not with something that happens *after* uninstalling.

That said, since Silo is a free tweak you can download it through Cyder3 on your PC and untar it there https://iosgods.com/topic/33906-release-cyder-30-download-cydia-deb-files-on-your-windows-desktop/
